[project]
name = "client"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "filbert251", email = "19623251@std.stei.itb.ac.id" }
]
requires-python = ">=3.12"
dependencies = [
    "windows-curses>=2.3.1"
]

[project.scripts]
client = "client:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
src = "src"
