[project]
name = "tou"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "filbert251", email = "19623251@std.stei.itb.ac.id" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
tou = "tou:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
